# Generated by Django 4.0.3 on 2023-09-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_appointment_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='vip',
        ),
    ]
